### ISSUE TITLE
[wpf] Property system

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs-desktop#1155]
Related to #60

@v-trisshores user story 1878471

- [x] WPF property system
    - [x] Dependency properties ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-properties-overview)) #1160
    - [x] Attached properties ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/attached-properties-overview)) #1178
    - [x] Custom dependency properties ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/custom-dependency-properties)) #1189
    - [x] Dependency property metadata ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-property-metadata)) #1203
    - [x] Dependency property callbacks and validation ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-property-callbacks-and-validation)) #1210
    - [x] Framework property metadata ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/framework-property-metadata)) #1223
    - [x] Dependency property value precedence ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-property-value-precedence)) #1164
      - [x] Related issue: #1154
    - [x] Read-Only dependency properties ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/read-only-dependency-properties)) #1230
    - [x] Property value inheritance ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/property-value-inheritance)) #1261
    - [x] Dependency property security ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-property-security)) #1233
    - [x] Safe-constructor patterns for DependencyObjects ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/safe-constructor-patterns-for-dependencyobjects)) #1254
    - [x] Collection-type dependency properties ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/collection-type-dependency-properties)) #1173
      - [x] Related issue: #1142
    - [x] XAML loading and dependency properties ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/xaml-loading-and-dependency-properties)) #1257
    - [x] Common tasks
      - [x] Implement a dependency property ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-implement-a-dependency-property)) #1180
      - [x] Register an attached property ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-register-an-attached-property)) #1179
      - [x] Override metadata for a dependency property ([Link](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-override-metadata-for-a-dependency-property)) #1205

**Comment by v-trisshores** [comment]
What branch would you like me to create PRs on? (maybe a new `wpf-properties` branch for these articles?)
