### ISSUE TITLE
.NET Framework WinForms content migration

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs-desktop#4]
This is the new repo for WPF/WinForms 

**Tasks**
- [x] Move content from [.NET Docs](https://github.com/dotnet/docs)
- [x] Redirects file in [.NET Docs](https://github.com/dotnet/docs)
- [x] Edit links in the content that were for .NET Docs to point to the docs URL and not .md file.
- [x] Move snippets
